'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
   await queryInterface.bulkInsert('biblio', [
    {
      bibid: 1,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2021-09-15 16:26:36',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 2,
      call_nmbr1: '004.1',
      call_nmbr2: 'FOR',
      call_nmbr3: 'k',
      title: 'Komputer untuk bisnis',
      title_remainder: 'pendidikan dan hiburan',
      responsibility_stmt: 'Forrest M., Marc Stern',
      author: 'Forrest M.',
      topic1: 'Komputer',
      topic2: 'Bisnis',
      topic3: 'Computer',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 5,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2022-01-03 11:41:22',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 13,
      call_nmbr1: '005.262',
      call_nmbr2: 'MOJ',
      call_nmbr3: 'f',
      title: 'Fortran 77',
      title_remainder: '',
      responsibility_stmt: 'Richard Mojena, Roy Ageloff',
      author: 'Mojena, Richard',
      topic1: 'Komputer',
      topic2: '',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 6,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2021-12-28 21:56:05',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 13,
      call_nmbr1: '004.6',
      call_nmbr2: 'SUD',
      call_nmbr3: 'i',
      title: 'Instalasi dan aplikasi netware novell',
      title_remainder: '',
      responsibility_stmt: 'Agt. Hanung Sudibyono',
      author: 'Sudibyono, Agt. Hanung',
      topic1: 'Komputer',
      topic2: 'Aplikasi Novell',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 7,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2021-12-28 21:30:19',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 2,
      call_nmbr1: '001.642',
      call_nmbr2: 'FED',
      call_nmbr3: 'c',
      title: 'Creative microcomputing, for teacher and children',
      title_remainder: 'A sourcebook for ideas',
      responsibility_stmt: 'Barbara Feddern',
      author: 'Barbara Feddern',
      topic1: 'Komputer',
      topic2: 'Mikro komputer',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 8,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2020-01-28 10:12:58',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 3,
      call_nmbr1: 'RES 899.221 3',
      call_nmbr2: 'MOh',
      call_nmbr3: 'd',
      title: 'Daerah Tidak Bertuan',
      title_remainder: '',
      responsibility_stmt: 'Toha Mohtar',
      author: 'Toha Mohtar',
      topic1: 'Fiksi Indonesia',
      topic2: 'Sastra',
      topic3: 'Indonesian -- fiction',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 11,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2022-01-03 11:39:07',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 13,
      call_nmbr1: '005.133',
      call_nmbr2: 'KAD',
      call_nmbr3: 'p',
      title: 'Pemrograman dasar cobol untuk IBM PC 1',
      title_remainder: '',
      responsibility_stmt: 'Abdul Kadir',
      author: 'Abdul Kadir',
      topic1: 'Komputer',
      topic2: 'Cobol',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 21,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2010-04-05 08:57:55',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 2,
      call_nmbr1: '796.325',
      call_nmbr2: 'ROB',
      call_nmbr3: 'b',
      title: 'Bola voli',
      title_remainder: 'bimbingan, petunjuk, teknik bermain',
      responsibility_stmt: 'Bonnie Robison',
      author: 'Bonnie Robison',
      topic1: 'Olahraga',
      topic2: 'Bola voli',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 30,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2018-07-19 11:03:21',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 2,
      call_nmbr1: '001.51',
      call_nmbr2: 'CIT',
      call_nmbr3: 'p',
      title: 'Prinsip-prinsip dan Teknik Berkomunikasi',
      title_remainder: '',
      responsibility_stmt: 'Suhartin Citrobroto',
      author: 'Suhartin Citrobroto',
      topic1: 'Komunikasi',
      topic2: 'Communication',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 88,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2017-04-26 13:58:43',
      last_change_userid: 5,
      material_cd: 1,
      collection_cd: 2,
      call_nmbr1: '790.06',
      call_nmbr2: 'PAN',
      call_nmbr3: 'd',
      title: 'Dasar Teori Olah Raga dan Organisasi',
      title_remainder: '',
      responsibility_stmt: '',
      author: 'Panjaitan, A.P',
      topic1: 'Olahraga',
      topic2: 'Organisasi olah raga',
      topic3: 'Teori olah raga',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 63434,
      create_dt: '2020-08-04 11:15:39',
      last_change_dt: '2020-10-13 13:23:21',
      last_change_userid: 5,
      material_cd: 6,
      collection_cd: 2,
      call_nmbr1: '004.65',
      call_nmbr2: 'AHM',
      call_nmbr3: 'o',
      title: 'Otomatisasi administrasi jaringan dengan script phyton',
      title_remainder: '',
      responsibility_stmt: 'Ahmad Rosid Komarudin',
      author: 'Ahmad Rosid Komarudin',
      topic1: 'Jaringan komunikasi',
      topic2: 'Communication network',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 12916,
      create_dt: '2007-01-01 01:01:01',
      last_change_dt: '2017-07-05 10:38:33',
      last_change_userid: 5,
      material_cd: 6,
      collection_cd: 2,
      call_nmbr1: '899.2213',
      call_nmbr2: 'IND',
      call_nmbr3: 't',
      title: 'Turi-Turian Sian daerah Batak Toba',
      title_remainder: '',
      responsibility_stmt: 'A.N. Parda Sibarani.',
      author: '',
      topic1: 'Kesusastraan Indonesia-Batak.',
      topic2: 'Sastra',
      topic3: 'Batak',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 38045,
      create_dt: '2011-07-22 11:16:20',
      last_change_dt: '2020-04-07 21:54:18',
      last_change_userid: 5,
      material_cd: 6,
      collection_cd: 2,
      call_nmbr1: '900',
      call_nmbr2: 'HIS',
      call_nmbr3: 'h',
      title: 'The history of Herodotus',
      title_remainder: '',
      responsibility_stmt: 'Edited by E.H. Blakeney',
      author: '',
      topic1: 'Sejarah Kuno',
      topic2: 'Sejarah',
      topic3: 'History ancient',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 48286,
      create_dt: '2013-06-27 08:26:29',
      last_change_dt: '2013-07-17 14:33:01',
      last_change_userid: 5,
      material_cd: 5,
      collection_cd: 1,
      call_nmbr1: 'R 338.203',
      call_nmbr2: 'JAY',
      call_nmbr3: 'k',
      title: 'Kamus dasar agronomi',
      title_remainder: '',
      responsibility_stmt: 'Supraptono Djajadirana',
      author: 'Djajadirana, Supratono',
      topic1: 'Agronomi-Kamus',
      topic2: '',
      topic3: '',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 62223,
      create_dt: '2019-09-02 10:57:58',
      last_change_dt: '2020-02-11 13:44:03',
      last_change_userid: 5,
      material_cd: 4,
      collection_cd: 3,
      call_nmbr1: 'RES 391.009',
      call_nmbr2: 'CUM',
      call_nmbr3: 'u',
      title: 'Understanding fashion history',
      title_remainder: '',
      responsibility_stmt: 'Valerie Cumming',
      author: 'Cumming, Valerie',
      topic1: 'Fashion',
      topic2: 'Clothing',
      topic3: 'Pakaian',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
    {
      bibid: 59749,
      create_dt: '2018-01-31 14:06:38',
      last_change_dt: '2018-02-22 13:27:17',
      last_change_userid: 5,
      material_cd: 4,
      collection_cd: 2,
      call_nmbr1: '370.154',
      call_nmbr2: 'HAM',
      call_nmbr3: 't',
      title: 'Teori Motivasi dan Pengukurannya',
      title_remainder: 'analisis di bidang pendidikan',
      responsibility_stmt: 'Hamzah B. Uno; editor, Juswinanto',
      author: 'Hamzah, B. Uno',
      topic1: 'Psikologi pendidikan',
      topic2: 'Motivasi belajar',
      topic3: 'Education - psychology',
      topic4: '',
      topic5: '',
      opac_flg: 'Y'
    },
   ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('biblio', null, {});
  }
};
